#!/bin/bash

input=peer.csv

temp=`mktemp /tmp/tmp.XXXXXXX`

awk -F',' '{ if (line > 0) { printf("%s\t%d\n", $2, $3); printf("%s\t%d\n", $4, $5); printf("%s\t%d\n", $6, $7); printf("%s\t%d\n", $8, $9); } ++line; }' $input | sort -f > $temp

#cat $temp

sqlite3 $temp.db << EOF
create table peer_review_summary(
	name VARCHAR(64),
	score INT
);
.separator "\t"
.import $temp peer_review_summary
SELECT name, AVG(score), MIN(score), MAX(score)
	FROM peer_review_summary GROUP BY name;
EOF
